### ISSUE TITLE
Don't store desired Traffic Policy on the Ingress object.

### ISSUE THREAD

**Issue by linki** [zalando-incubator/stackset-controller#37]
It might makes sense to extract the information about the desired traffic policy into `StackSet`, `Stack` or a dedicated resource.

Currently, the desired traffic policy is stored as an annotation on the `Ingress` object (for historical reasons). We are already using a different annotation from what skipper needs [0] so there's really no reason to have the new annotation on the `Ingress`.

It should either be a real field on:
* The `StackSet`, since it already defines the corresponding DNS name that's traffic switched
* The individual Stack objects could have a traffic weight field on themselves
* A dedicated resource `TrafficPolicy` that describes how traffic is shaped and doesn't live in the `StackSet`

[0] we set `zalando.org/stack-traffic-weights` and skipper reads `zalando.org/backend-weights`

**Comment by mikkeloscar** [comment]
> The individual Stack objects could have a traffic weight field on themselves

This is how I initially implemented it. It has the problem that you can't really modify the traffic weights in a transaction, so you could end up setting 0 on one stack and fail to set 100 on the other resulting in undesired traffic distribution.
However we do it, it should be something you can modify on a single resource.

@szuecs had some thoughts around a `SkipperRoute` resource type which is related and also could be considered here IMO.

**Comment by szuecs** [comment]
I think it makes sense to store it in StackSet and distribute to ingress, because for http routers it does not makes sense to "integrate" with stackset, it should be the stackset-contrller making the change happen to ingress. The advantage with ingress is that other controller like traefik already support zalando.org/backend-weights, so we should not change that for skipper or as target.

SkipperRoute should only be used in favor for custom-routes, in my opinion. Maybe the idea will expand, but I did not started yet with the SkipperRoute anyways.

**Comment by mikkeloscar** [comment]
My concern with having it directly on the `StackSet` resource is that it becomes quite hard to just reapply the `StackSet` because the list of traffic distribution is dynamic so you would have to always modify the stackset resource you are applying to have the desired traffic distribution.

**Comment by szuecs** [comment]
@mikkeloscar I am fine with only having it in the ingress.
We have to have the 2 annotations anyways to have the desired -> current.

**Comment by szuecs** [comment]
No answer and we store now the values in stackset `spec.Traffic` and `status.Traffic`
